# Generated by Django 2.2.3 on 2019-07-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190718_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
    ]
