# Generated by Django 2.2.3 on 2019-07-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190718_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='user_id',
            new_name='user',
        ),
    ]
