# Generated by Django 2.2.3 on 2019-07-21 09:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190721_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, null=True, size=None),
        ),
    ]
