# Generated by Django 2.2.3 on 2019-07-28 08:50

import api.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_resource_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Tags contain invalid characters.', regex='^[A-Za-z0-9_ \\u0370-\\u03ff\\u1f00-\\u1fff]*$')]), default=[], size=None, validators=[api.validators.validate_no_duplicates]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(code='inv_char', message='Title contains invalid characters.', regex='^[A-Za-z0-9_ \\u0370-\\u03ff\\u1f00-\\u1fff]*$')]),
        ),
    ]
