# Generated by Django 2.2.3 on 2019-07-28 08:57

import api.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190728_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='note',
            field=models.CharField(blank=True, default=str, max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60, validators=[django.core.validators.RegexValidator(message='Tags contain invalid characters.', regex='^[A-Za-z0-9_ \\u0370-\\u03ff\\u1f00-\\u1fff]*$')]), default=list, size=None, validators=[api.validators.validate_no_duplicates]),
        ),
    ]
