# Generated by Django 2.2.3 on 2019-08-07 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20190728_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sorting', models.CharField(choices=[('AS', 'Ascending'), ('DE', 'Descending'), ('NO', 'None')], default='AS', max_length=2)),
                ('title_sorting', models.CharField(choices=[('AS', 'Ascending'), ('DE', 'Descending'), ('NO', 'None')], default='NO', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
