# Generated by Django 2.2.3 on 2019-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190807_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='time_sorting',
        ),
        migrations.RemoveField(
            model_name='option',
            name='title_sorting',
        ),
        migrations.AddField(
            model_name='option',
            name='sorting',
            field=models.CharField(choices=[('TAS', 'Time Ascending'), ('TDE', 'Time Descending'), ('AAS', 'Alphab Ascending'), ('ADE', 'Alphab Descending'), ('NOS', 'No Sorting')], default='TAS', max_length=3),
        ),
    ]
