# Generated by Django 2.2.3 on 2019-08-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190807_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='sorting',
            new_name='sort',
        ),
    ]
